services:
  api:
    environment:
      NODE_ENV: development

  web:
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000/api/v1

  worker:
    environment:
      NODE_ENV: development